[project]
name = "task-06-k8s"
version = "0.1.0"
description = "Add your description here"
authors = [
    { name = "Evgenii Gorohov", email = "e.n.gorohov@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "kubernetes>=36.0.3",
]

[project.scripts]
task-06-k8s = "task_06_k8s:main"

[build-system]
requires = ["uv_build>=0.12.21,<0.13.0"]
build-backend = "uv_build"
